"""Create tables

Revision ID: 572e10c91141
Revises: 
Create Date: 2024-02-21 18:13:01.794866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572e10c91141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   # op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
   # op.drop_column('employees', 'department_id')
    # ### end Alembic commands ###
